
jerseyClient:
  timeout: 10000ms
  connectionTimeout: 10000ms
  timeToLive: 1 hour
  cookiesEnabled: false
  maxConnections: 100
  maxConnectionsPerRoute: 100
  keepAlive: 0s
  minThreads: 1
  maxThreads: 1000
  gzipEnabled: false
  gzipEnabledForRequests: false

dataSource:
  driverClass: com.mysql.jdbc.Driver
  user: bragnolabel_ro
  password: bragnolabel@123
  url: jdbc:mysql://localhost/bragnolabel?nullNamePatternMatchesAll=true

server:
  applicationConnectors:
  - type: http
    port: 9999
  adminConnectors:
  - type: http
    port: 9991

logging:
  level: DEBUG
  loggers:
   org.hibernate: WARN
  appenders:
  - type: console
    threshold: DEBUG


logging:
  level: INFO
  loggers:
   org.hibernate: WARN
  appenders:
    - type: file
      currentLogFilename: /var/log/LPIntegrator/integratorApi.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /var/log/LPIntegrator/integratorApi-%d%i.log
      archivedFileCount: 5
      timeZone: UTC
      logFormat: # TODO
      maxFileSize: 20MB
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: # TODO
