package com.shopify.api.models;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import io.dropwizard.jackson.JsonSnakeCase;
import lombok.Data;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

@JsonSnakeCase
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class Order{
	
	private String cart_token;

	private String checkout_id;

	private String phone;

	private String contact_email;

	private String gateway;

	private String test;

	private String total_weight;

	private String referring_site;

	private Customer customer;

//	private String[] discount_codes;

	private String confirmed;

	private String subtotal_price;

	private String checkout_token;

	private String total_line_items_price;

	private String fulfillment_status;

	private String order_number;

	private List<LineItems> line_items;

	private String closed_at;

	private String total_price_usd;

	private ShippingLine[] shipping_lines;

	private String total_discounts;

	//private String[] note_attributes;

	private String number;

	private String cancelled_at;

	private String buyer_accepts_marketing;

	private String total_price;

	private String[] payment_gateway_names;

	private String processed_at;

	private String updated_at;

	private String email;

	private String[] refunds;

	private String app_id;

	private ShopifyAddress billing_address;

	private String order_status_url;

	private String landing_site_ref;

	private String source_url;

	private TaxLines[] tax_lines;

	private String currency;

	private ShopifyAddress shipping_address;

	private String id;

	private String token;

	private String name;

	private String created_at;

	private String user_id;

	private String source_name;

	private String total_tax;

	private String note;

	private String cancel_reason;

	private String tags;

	private Fulfillment[] fulfillments;

	private String browser_ip;

	private String device_id;

	private String taxes_included;

	private String reference;

	private String location_id;

	private String financial_status;

	private String customer_locale;

	private String processing_method;

	private String source_identifier;

	private String landing_site;
	
	private ClientDetails client_details;
	
	private PaymentDetails payment_details;

	@Override
	public String toString()
	{
		return "[cart_token = "+cart_token+", checkout_id = "+checkout_id+", phone = "+phone+", contact_email = "+contact_email+", gateway = "+gateway+", test = "+test+", total_weight = "+total_weight+", referring_site = "+referring_site+", customer = "+customer+", discount_codes = , confirmed = "+confirmed+", subtotal_price = "+subtotal_price+", checkout_token = "+checkout_token+", total_line_items_price = "+total_line_items_price+", fulfillment_status = "+fulfillment_status+", order_number = "+order_number+", line_items = "+line_items+", closed_at = "+closed_at+", total_price_usd = "+total_price_usd+", shipping_lines = "+shipping_lines+", total_discounts = "+total_discounts+", note_attributes = , number = "+number+", cancelled_at = "+cancelled_at+", buyer_accepts_marketing = "+buyer_accepts_marketing+", total_price = "+total_price+", payment_gateway_names = "+payment_gateway_names+", processed_at = "+processed_at+", updated_at = "+updated_at+", email = "+email+", refunds = "+refunds+", app_id = "+app_id+", billing_address = "+billing_address+", order_status_url = "+order_status_url+", landing_site_ref = "+landing_site_ref+", source_url = "+source_url+", tax_lines = "+tax_lines+", currency = "+currency+", shipping_address = "+shipping_address+", id = "+id+", token = "+token+", name = "+name+", created_at = "+created_at+", user_id = "+user_id+", source_name = "+source_name+", total_tax = "+total_tax+", note = "+note+", cancel_reason = "+cancel_reason+", tags = "+tags+", fulfillments = "+fulfillments+", browser_ip = "+browser_ip+", device_id = "+device_id+", taxes_included = "+taxes_included+", reference = "+reference+", location_id = "+location_id+", financial_status = "+financial_status+", customer_locale = "+customer_locale+", processing_method = "+processing_method+", source_identifier = "+source_identifier+", landing_site = "+landing_site+"]";
	}
}